### ISSUE TITLE
Text in Terminal is not properly aligned

### ISSUE THREAD

**Issue by 0x15F9** [LukeGarrigan/hacktober-race#17]
![misaligned text](https://user-images.githubusercontent.com/17203172/66248952-3b46e000-e73e-11e9-894e-4d747c5d8525.png)

**Comment by 0x15F9** [comment]
I can fix it

**Comment by LukeGarrigan** [comment]
I believe this has already been fixed with changes in https://github.com/LukeGarrigan/hacktober-race/issues/17
