### ISSUE TITLE
Error: Cannot GET /

### ISSUE THREAD

**Issue by harveysanders** [LukeGarrigan/hacktober-race#24]
For some reason, the relative path for the public directory does not work on my machine. I'll put in a PR to use an absolute path for `express.static()`. This should work on everyone's machine.

Fun project!

**Comment by LukeGarrigan** [comment]
What is the reason this happens?

**Comment by LukeGarrigan** [comment]
I'll merge it anyway, would like to know the reasoning though, I'm a curious lad 😁
