### ISSUE TITLE
Add a blinking cursor

### ISSUE THREAD

**Issue by LukeGarrigan** [LukeGarrigan/hacktober-race#7]
When typing it would be nice to have either underneath the letter you're currently on or to the left of it to have a blinking cursor just so it's easy to track where you currently are.

**Comment by mtrunt** [comment]
I'd like to take this.

**Comment by LukeGarrigan** [comment]
merged in https://github.com/LukeGarrigan/hacktober-race/commit/f3d8a3567a1e6953f654938f2291b9cd26910bad

**Comment by LukeGarrigan** [comment]
Also don't forget to leave a star ⭐ Let's spread the word!
